### ISSUE TITLE
WSL2 on Win X 21H! yarn install fails - if this is not supported - delete issue

### ISSUE THREAD

**Issue by comtechnet** [nounsDAO/nouns-monorepo#245]
Cloned the repo in Ubuntu 20.04.2 (which is a WSL2 linux instance) and proceedd with the Yarn (install) ...

make: Entering directory '/home/comtechnet/nouns/node_modules/node-hid/build'
  CC(target) Release/obj.target/hidapi-linux-hidraw/hidapi/linux/hid.o
  AR(target) Release/obj.target/hidapi-linux-hidraw.a
  COPY Release/hidapi-linux-hidraw.a
  CXX(target) Release/obj.target/HID-hidraw/src/HID.o
../src/HID.cc:71:5: warning: dynamic exception specifications are deprecated in C++11 [-Wdeprecated]
   71 |     throw(JSException);
      |     ^~~~~
../src/HID.cc:74:5: warning: dynamic exception specifications are deprecated in C++11 [-Wdeprecated]
   74 |     throw(JSException);
      |     ^~~~~
../src/HID.cc:156:3: warning: dynamic exception specifications are deprecated in C++11 [-Wdeprecated]
  156 |   throw(JSException)
      |   ^~~~~
../src/HID.cc:167:3: warning: dynamic exception specifications are deprecated in C++11 [-Wdeprecated]
  167 |   throw(JSException)
      |   ^~~~~

IS THIS SUPPORTED or expected?  If NOT - just close the issue and I'll move on  - Thanks!

**Comment by comtechnet** [comment]
make: *** [HID-hidraw.target.mk:124: Release/obj.target/HID-hidraw/src/HID.o] Error 1
make: Leaving directory '/home/comtechnet/nouns/node_modules/node-hid/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/comtechnet/nouns/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (node:events:365:28)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)
gyp ERR! System Linux 5.4.72-microsoft-standard-WSL2
gyp ERR! command \"/home/comtechnet/.nvm/versions/node/v16.2.0/bin/node\" \"/home/comtechnet/nouns/node_modules/.bin/node-gyp\" \"rebuild\"
gyp ERR! cwd /home/comtechnet/nouns/node_modules/node-hid

**Comment by solimander** [comment]
`node-hid`, which causes this warning, is an optional sub-dependency of `@web3-react/ledger-connector`. This warning is ugly, but does not otherwise cause any issues. Closing this issue.
