### ISSUE TITLE
Investigate isMobileScreen working while idle

### ISSUE THREAD

**Issue by bcjgit** [nounsDAO/nouns-monorepo#334]

**Comment by bcjgit** [comment]
From convo with @cryptoseneca 

> heads up: i have a hunch isMobileScreen will stop working while idle so we might need to fix, if true
effect would be seeing the mobile "switch | disconnect" menu while on desktop

**Comment by cryptoseneca** [comment]
Closed due to issue appearing only when going from desktop to mobile on chrome dev tools
