### ISSUE TITLE
Duplicate ```import '@nomiclabs/hardhat-waffle';``` statement in Hardhat config file for Nouns contracts package.

### ISSUE THREAD

**Issue by metamonk** [nounsDAO/nouns-monorepo#369]
```@nomiclabs/hardhat-waffle``` package is imported twice in [packages/nouns-contracts/hardhat.config.ts](https://github.com/nounsDAO/nouns-monorepo/blob/28b0bb44b2e241ecb3f0eb6b24c94881cd7c8922/packages/nouns-contracts/hardhat.config.ts)

**Comment by solimander** [comment]
Closed in #428
