### ISSUE TITLE
Nouns Webapp - running local, but error when bidding

### ISSUE THREAD

**Issue by rmwa** [nounsDAO/nouns-monorepo#569]
Got the Nouns Webapp up and running locally, but bidding / settling is not working.
The following error message appears after I confirm the transaction in Metamask.

Any idea what this can fix ?!

Error
[ethjs-query] while formatting outputs from RPC '{"value":{"code":-32603,"data":{"code":-32000,"message":"Nonce too high. Expected nonce to be 26 but got 42. Note that transactions can't be queued when automining.","data":{"message":"Nonce too high. Expected nonce to be 26 but got 42. Note that transactions can't be queued when automining."}}}}'

<img width="553" alt="image" src="https://user-images.githubusercontent.com/1593564/190857800-6a7cab60-d35c-46b0-a5d7-8cedcb4b93c9.png">

**Comment by solimander** [comment]
MetaMask is using a cached nonce that is no longer valid for the local chain. You can [reset the account](https://metamask.zendesk.com/hc/en-us/articles/360015488891-How-to-reset-an-account) in MetaMask to fix this issue.
