### ISSUE TITLE
Upgrade WalletConnect to V2

### ISSUE THREAD

**Issue by Lemma199** [nounsDAO/nouns-monorepo#740]
Creating this issue to track upgrading the webapp to use WalletConnect V2, since V1 is being sunset (See https://docs.walletconnect.com/2.0/advanced/migration-from-v1.x/overview). Inspired by [this Tweet](https://twitter.com/awkweb/status/1673327796309966859) by @tmm.

The webapp uses `web3-react` to include the WalletConnect connector, and there is a separate V2 package https://github.com/Uniswap/web3-react/tree/main/packages/walletconnect-v2.

**Comment by tmm** [comment]
Unfortunately the current web3-react version (v8) that supports WalletConnect v2 does not support the web3-react version Nouns is using (v6). Probably the easiest thing to do is fork the [WalletConnect connector source code](https://github.com/Uniswap/web3-react/blob/v6/packages/walletconnect-connector/src/index.ts) into the codebase and update it to use WalletConnect v2.

**Comment by Lemma199** [comment]
I'll poke around today and see how much effort upgrading `web3-react` from `v6` to `v8` is going to be for the Nouns webapp. This might be a productive effort in the long-run. I think the challenging bit might be refactoring the "state management patterns" ([web3-react docs link](https://github.com/Uniswap/web3-react#upgrading-from-v6)), I'll update this ticket later today/tomorrow with whatever I find.

**Comment by Lemma199** [comment]
**Update:** I tried upgrading the dependencies and refactoring the codebase, but the effort required is a bit more involved. Moving from `v6` to `v8` also requires upgrading the `ethers` library which has some backward incompatible changes that require yet more refactoring. I'll take another look at this tomorrow and see if there is an easier path to integrating WalletConnect `v2` _without_ upgrading the rest of the world.

**Comment by Lemma199** [comment]
Spent a bit more time on this today trying to get this working based on https://github.com/Uniswap/web3-react/issues/755#issuecomment-1598808384 but could not get things working. Unfortunately I don't have more time between now and the WalletConnect V2 migration cut-off time (**June 28, 2023 at 2pm (UTC)**) to continue working on this.

Some other notes:
- WalletConnect V2 requires a `projectId`, someone with access to the Nouns WalletConnect dashboard will need to add this

Tagging @solimander (last commits on the repo) since there's some urgency around this.

**Comment by solimander** [comment]
Thanks for the ping @Lemma199! I'll get this working and deployed today. Appreciate your contributions 🙏
