### ISSUE TITLE
getCurrentVotes takes a long time to resolve for Alchemy and Infura

### ISSUE THREAD

**Issue by TimDaub** [nounsDAO/nouns-monorepo#865]
- I'm the admin of Kiwi News: https://kiwinews.xyz
- We currently run a writers contest with nouns (we've won a prop)
- One eligibility criteria that makes a vote from a Noun count is that their `getCurrenVotes` balance on the Mainnet contract is > 0
- Here's that code https://github.com/attestate/kiwistand/blob/e6f348cda03ae18f67de7c83756b5b9f8cb48f1b/src/views/feed.mjs#L70-L94
- Specifically the `const votes = await contract.getCurrentVotes(address);` statement takes a very long time. I measured this multiple times

However, for the entire day I have debugged this and while the call generally works, on Infura and Alchemy, it can take up to 90 seconds per address to resolve. This is too long for us to deliver the HTML page. I could, of course, load this on the side and always serve it when its needed through a cache.

But I came here to first ask whether there's an alternative source of that data that I can use. We've already explored the Nouns subgraph, but we didn't find an equivalent solution

```
{
  accounts(where: {id_in: ["0xcb22cc5d24e6cf280fac2a107568aaa8c8373276"]}) {
    id
    totalTokensHeld
    totalTokensHeldRaw
  }
}
```

e.g. this one won't show the delegated Nouns.

I'd also like to know why it is that getCurrentVotes takes so long. When I looked into its implementation, I didn't see any issue with the function's runtime complexity:

![photo_2024-10-23 21 47 40](https://github.com/user-attachments/assets/9361d1c4-bb9b-4aa7-83bd-cffcf058c492)

Still, I might be missing something if the scope of the function requires a lot of memory and hence causes the RPC providers to take a while to respond.

Anyways, if you know a way how I can make that query in a faster way it would be very helpful!

**Comment by spennyp** [comment]
This view function has a constant time complexity and should return fast.

From a quick test, it does:
```ts
import { multicall, readContract } from "viem/actions";
import { Address, createClient, getAddress, http } from "viem";
import { mainnet } from "viem/chains";

const NOUNS_TOKEN_CONTRACT = {
  address: getAddress("0x9C8fF314C9Bc7F6e59A9d9225Fb22946427eDC03"),
  abi: [
    {
      inputs: [{ internalType: "address", name: "account", type: "address" }],
      name: "getCurrentVotes",
      outputs: [{ internalType: "uint96", name: "", type: "uint96" }],
      stateMutability: "view",
      type: "function",
    },
  ] as const,
};

const viemClient = createClient({
  chain: mainnet,
  transport: http("https://eth.merkle.io"), // You should use your own RPC endpoint here
});

async function getCurrentVotesForAddress(address: Address): Promise<bigint> {
  return await readContract(viemClient, {
    ...NOUNS_TOKEN_CONTRACT,
    functionName: "getCurrentVotes",
    args: ["0x65599970Af18EeA5f4ec0B82f23B018fd15EBd11"],
  });
}

async function getCurrentVotesForAddresses(addresses: Address[]): Promise<bigint[]> {
  return await multicall(viemClient, {
    contracts: addresses.map((address) => ({
      ...NOUNS_TOKEN_CONTRACT,
      functionName: "getCurrentVotes",
      args: [address],
    })),
    allowFailure: false,
  });
}

async function run() {
  const t0 = performance.now();

  const votesForAddress = await getCurrentVotesForAddress("0x65599970Af18EeA5f4ec0B82f23B018fd15EBd11");

  const t1 = performance.now();

  const votesForAddresses = await getCurrentVotesForAddresses([
    "0x65599970Af18EeA5f4ec0B82f23B018fd15EBd11",
    "0x86030dbbce1c771ff6622c20455cd3619aa93c05",
    "0x99635729e1402847cd2ce4933688bcf7211fdd7e",
    "0x83fcfe8ba2fece9578f0bbafed4ebf5e915045b9",
    "0xae65e700f3f8904ac1007d47a5309dd26f8146c0",
    "0xae7f458667f1b30746354abc3157907d9f6fd15e",
    "0x75ca7ad7a0088f131abe8c11afec969ff15c3f73",
  ]);

  const t2 = performance.now();

  console.log(`Votes for address: ${votesForAddress}, time: ${t1 - t0}ms`);
  console.log(`Votes for addresses: ${votesForAddresses}, time: ${t2 - t1}ms`);
}

run();
```

The output
```bash
Votes for address: 2, time: 307.77308300000004ms
Votes for addresses: 2,65,43,25,22,15,14, time: 128.17649999999992ms
```

I suspect the latency is coming from elsewhere besides this contract read. 
Might be helpful to put some timing inside the slow function to isolate the true cause.

**Comment by TimDaub** [comment]
Yeah, you're right I isolated the function and by itself I don't run into the same issue. 

```
import { env } from "process";
import ethers from "ethers";

import cache from "./cache.mjs";
import { logd } from "./utils.mjs";

const provider = new ethers.providers.JsonRpcProvider(env.RPC_HTTP_HOST);
export async function getNounsVotes(address) {
  const cacheKey = `nouns-votes-${address}`;
  if (cache.has(cacheKey)) {
    return cache.get(cacheKey);
  }

  const contractAddress = "0x9c8ff314c9bc7f6e59a9d9225fb22946427edc03";
  const abi = [
    {
      inputs: [{ internalType: "address", name: "account", type: "address" }],
      name: "getCurrentVotes",
      outputs: [{ internalType: "uint96", name: "", type: "uint96" }],
      stateMutability: "view",
      type: "function",
    },
  ];

  const contract = new ethers.Contract(contractAddress, abi, provider);
  logd(`pre votes ${address}`);
  const votes = await contract.getCurrentVotes(address);
  logd(`post votes ${address}`);

  const votesNumber = votes.toNumber();
  cache.set(cacheKey, votesNumber);
  return votesNumber;
}

await getNounsVotes("0xcb22cc5d24e6cf280fac2a107568aaa8c8373276");
await getNounsVotes("0xee324c588ceF1BF1c1360883E4318834af66366d");
await getNounsVotes("0x3e6c23CdAa52B1B6621dBb30c367d16ace21F760");
await getNounsVotes("0xBc59BC6F063287e63C4df600a0F8f768AA778480");
```

node -r dotenv/config src/nounstest.mjs
pre votes 0xcb22cc5d24e6cf280fac2a107568aaa8c8373276: Delta: 0ms
post votes 0xcb22cc5d24e6cf280fac2a107568aaa8c8373276: Delta: 1309ms
pre votes 0xee324c588ceF1BF1c1360883E4318834af66366d: Delta: 1ms
post votes 0xee324c588ceF1BF1c1360883E4318834af66366d: Delta: 848ms
pre votes 0x3e6c23CdAa52B1B6621dBb30c367d16ace21F760: Delta: 0ms
post votes 0x3e6c23CdAa52B1B6621dBb30c367d16ace21F760: Delta: 855ms
pre votes 0xBc59BC6F063287e63C4df600a0F8f768AA778480: Delta: 1ms
